### ISSUE TITLE
Create Spy Provider

### ISSUE THREAD

**Issue by taylor-ben** [hirezio/auto-spies#26]
Create a spy provider with less code, which is less prone to error.

**Comment by shairez** [comment]
Thanks Ben!

You're on the right track, next time you just need to create a pull request from the forked repo you made your changes in. 

But I think it will be better to keep jasmine-auto-spies agnostic to front end frameworks, so this might be better done as a plugin. 

When we'll move this repo into a monorepo, this could become another package (like angular plugin or something like that)

**Comment by shairez** [comment]
After thinking about it, it's a very small file to add .. I don't think the overhead of a separate library justifies it. 

So I'll include it in the packages after all (if in the future we'll see that we need more Angular specific utils we'll extract it out)

Thanks for the contribution @taylor-ben !
