### ISSUE TITLE
Type 'HttpClient' is not assignable to type 'AddAutoSpies<HttpClient, Spy<Func>>'.

### ISSUE THREAD

**Issue by maximaexchen** [hirezio/auto-spies#28]
**Describe the bug**
Cannot create spy fromm HTTPClient

**To Reproduce**

...
let httpSpy: Spy<HttpClient>;
....
providers:
{ provide: HttpClient, useValue: createSpyFromClass(HttpClient) }
....
httpSpy = TestBed.inject(HttpClient);

**Desktop (please complete the following information):**

"@angular/core": "~10.0.0",
"jasmine-auto-spies": "^6.3.4",

**Additional context**
```
error TS2322: Type 'HttpClient' is not assignable to type 'Spy<HttpClient>'.
  Type 'HttpClient' is not assignable to type 'AddAutoSpies<HttpClient, Spy<Func>>'.
    Types of property 'request' are incompatible.
```

**Comment by shairez** [comment]
Thanks for the report @maximaexchen !

You need to use `any` when you inject spies - 

```js
httpSpy = TestBed.inject<any>(HttpClient);
```

I've also added [an explanation about it in the docs](https://github.com/hirezio/auto-spies/tree/master/packages/jasmine-auto-spies#-angular-developers---use-testbedinjectany)

**Comment by maximaexchen** [comment]
Thanks Shai.
That did it. Thanks for adding it.

**Comment by shairez** [comment]
Sure thing!

I'm going to close this issue as it is resolved :)

Have a great day!
