### ISSUE TITLE
Typo in the docs

### ISSUE THREAD

**Issue by ldex** [hirezio/auto-spies#35]
**Describe the bug**
Small typo in the jasmine-auto-spies readme file.

**To Reproduce**
On this page:
https://github.com/hirezio/auto-spies/tree/master/packages/jasmine-auto-spies

On the "Usage (TypeScript)" section, we can read:
import { Spy, createSpyFromClass } from 'jest-auto-spies';

**Expected behavior**
It should be:
import { Spy, createSpyFromClass } from 'jasmine-auto-spies';

**Comment by shairez** [comment]
You are correct sir! 🙏

Wanna fix it and become a contributor? 💪😀

**Comment by ldex** [comment]
sure!

Le lun. 26 oct. 2020, à 09 h 56, Shai Reznik <notifications@github.com> a
écrit :

**Comment by shairez** [comment]
Thanks again for your contribution!
