### ISSUE TITLE
Spy on readonly property

### ISSUE THREAD

**Issue by flowest** [hirezio/auto-spies#37]
Wouldn't it be good, to spy on a readonly property?

**Comment by shairez** [comment]
Basically, a readonly property is the same as a property with only a getter. 

So you can configure it by using the [`gettersToSpyOn` configuration property](https://github.com/hirezio/auto-spies/tree/master/packages/jasmine-auto-spies#-create-accessors-spies-getters-and-setters)

as so - 

```js
// some-class.js

export class SomeClass {
  public readonly someReadOnlyProp = 4;
}

// my-test.js

beforeEach(()=>{

   someClassSpy = createSpyFromClass(SomeClass, {
      gettersToSpyOn: ['someReadOnlyProp'],
   });

  // This is using the jest API but you can do it for jasmine as well - 
  someClassSpy.accessorSpies.getters.someReadOnlyProp.mockReturnValue(333);

  console.log(someClassSpy.someReadOnlyProp) // LOGS: 333 
});


```
