### ISSUE TITLE
add 'nextWith' when testing Getters which are returning an Observable

### ISSUE THREAD

**Issue by pielle87** [hirezio/auto-spies#43]
**Is your feature request related to a problem? Please describe.**
I have a private BehaviorSubject in a service, which I am returning as an Observable. Something like:
![image](https://user-images.githubusercontent.com/10289355/108635505-fbda7a00-747f-11eb-808f-66691ae5b4d1.png)

I followed the approach to test a getter, but my IDE did not display the usual functions for testing Observables (e.g. `nextWith`)
![image](https://user-images.githubusercontent.com/10289355/108635870-17df1b00-7482-11eb-9629-9ac40a4ad751.png)

**Describe the solution you'd like**
Although I was able to complete my test without them, it'd make things easier if the 'getters' approach took the return type of the getter itself into account.

**Describe alternatives you've considered**
I was able to work around the problem by using the function `returnValue`, which was suggested by the IDE.

**Comment by shairez** [comment]
Thanks @pielle87 and sorry for the late reply

You can use `observablePropsToSpyOn` and you'll get this functionality 

Does that solve your issue? (if not, feel free to re-open this issue)
