### ISSUE TITLE
Support for RxJs 7

### ISSUE THREAD

**Issue by rainerhahnekamp** [hirezio/auto-spies#52]
Is it possible to set the peerDependencies of RxJs to > 6? I am currently using it successfully with RxJs 7.4 but always get a warning when running `npm install`.

**Comment by shairez** [comment]
Sure Rainer!
But I think maybe a `< 8` will be safer for the future automatic upgrades
Want to create a PR for it? :)

**Comment by rainerhahnekamp** [comment]
True, let me come back with a PR for it then. 👍

**Comment by shairez** [comment]
Thanks @rainerhahnekamp ! 🙏

**Comment by hokrc01** [comment]
I needed to do the following npm install -D --force jasmine-auto-spies.
Has this been completed yet

**Comment by hokrc01** [comment]
It loaded no issue.  Thank you

**Comment by shairez** [comment]
Thanks for the feedback @hokrc01 🙏
