### ISSUE TITLE
Working tests fail after upgrade to Angular 13 with strict typing

### ISSUE THREAD

**Issue by hokrc01** [hirezio/auto-spies#56]
**Describe the bug**

> Error: projects/admin/src/app/services/event-runner.service.spec.ts:178:33 - error TS2339: Property 'nextWith' does not exist on type 'SpyAnd<Func> | (SpyAnd<Func> & AddPromiseSpyMethods<unknown>) | (SpyAnd<Func> & AddObservableSpyMethods<unknown>)'.
>   Property 'nextWith' does not exist on type 'SpyAnd<Func>'.
> 
> 178         apiServiceSpy.fetch.and.nextWith(fakeResponse);

**To Reproduce**
Sample code :

```
const setPayload = (payload:any) => {
      const fakeResponse = payload;
      apiServiceSpy.fetch.and.nextWith(fakeResponse);
    };
```

**Expected behavior**
This test sample ran under 11.  As a work around, I have blanked it out.  In doing so, I have lost most of my existing tests

**Comment by shairez** [comment]
Without seeing the whole code I cannot trace down the problem 
Can you please upload a sample project to github that simulates this issue?

**Comment by shairez** [comment]
Closing this for lack of response
when you'll have time to reproduce and maybe share a repo, you can re-open

thanks
