### ISSUE TITLE
Make jasmine-auto-spies compatible with jasmine-core 4

### ISSUE THREAD

**Issue by WynieCronje** [hirezio/auto-spies#58]
**Is your feature request related to a problem? Please describe.**
jasmine-auto-spies is not compatible with new version of jasmine-core

**Additional context**
[Dependency Config](https://github.com/hirezio/auto-spies/blob/e5632d7368fa2b5b96a5b4e5eb9af3eaff202424/packages/jasmine-auto-spies/package.json#L49)

**Comment by WynieCronje** [comment]
I upgraded locally and did not seem like anything was broken (all tests passed).

I did some further investigation. and found [these breaking changes](https://jasmine.github.io/tutorials/upgrading_to_Jasmine_4.0) of jasmine between v3 and v4.

Nothing seems to be related to Spies. 

I think It's safe to assume that this plugin is compatible with jasmine v4

**Comment by shairez** [comment]
Thanks for the issue and PR @WynieCronje ! 🙏
Yeah by reading the breaking changes doc I don't see anything that should affect auto-spies

I'll merge your PR now

Thanks again!
