### ISSUE TITLE
Bump Jest Version Supported to Jest v28

### ISSUE THREAD

**Issue by mtpultz** [hirezio/auto-spies#62]
**Is your feature request related to a problem? Please describe.**
Dependency on Jest <  28.x.

**Describe the solution you'd like**
Update the dependencies to allow for Jest v28.x.

**Describe alternatives you've considered**
Downgrading Jest to v27, but package appears to work under v28.

**Comment by shairez** [comment]
Thanks @mtpultz 

Want to open a PR for that? :)

**Comment by gestj** [comment]
Heyho @shairez 

this is starting to hurt me really badly. I stand before the question to downgrade Jest again to 27 in my project or throw `jest-auto-spies` out once again... 

I guess, I go with second since that isn't as painful as downgrading.

Best regards Johannes

**Comment by shairez** [comment]
https://stackoverflow.com/questions/14187956/npm-install-from-git-in-a-specific-version
