### ISSUE TITLE
npm release of jest-auto-spies@1.6.11 failed

### ISSUE THREAD

**Issue by mserwicki** [hirezio/auto-spies#68]
I just wanted to let you know that something went wrong with the release of version @1.6.11
https://github.com/hirezio/auto-spies/actions/runs/4303640906

It would be great to use the package with jest@29 as nx moved to that in their 15.8.x update

**Comment by mserwicki** [comment]
oh, I thought it was caused only by missing some secrets - credentials for npm

![image](https://user-images.githubusercontent.com/55290524/226351898-4e82dfe2-364a-4897-acb4-1bf7e46a867e.png)

Was not aware it requires more work, thank you very much for the replay.

**Comment by shairez** [comment]
@mserwicki  yeah that's why I switched to pnpm, but upgrading in general caused more issues related to webpack, typescript etc

**Comment by shairez** [comment]
OK it's fixed now 😊
thanks @mopinsk for your PR 🙏
