### ISSUE TITLE
Make jasmine-auto-spies compatible with jasmine-core 5

### ISSUE THREAD

**Issue by jpgoelz** [hirezio/auto-spies#76]
**Is your feature request related to a problem? Please describe.**
_jasmine-auto-spies_ is not compatible with the current version of jasmine-core ([v5.x](https://github.com/jasmine/jasmine/blob/main/release_notes/5.0.0.md))

**Describe the solution you'd like**
Compatibility with the most current version of Jasmine

**Describe alternatives you've considered**
n/a

**Additional context**
[Current dependency restrictions](https://github.com/hirezio/auto-spies/blob/e433d8d3d012c8c38dfec53b13487214b47322fa/packages/jasmine-auto-spies/package.json#L48C35-L48C35)

Thank you! 🥳

**Comment by shairez** [comment]
Would you mind creating a PR to fix that please?

**Comment by jpgoelz** [comment]
Will do that asap!

**Comment by shairez** [comment]
awesome thanks!

**Comment by jpgoelz** [comment]
There you go!

It only took a few mistakes in my commit messages (which GitHub so generously points out for the history books 😅).
