### ISSUE TITLE
next* observable functions when withArgs is used

### ISSUE THREAD

**Issue by Zooce** [hirezio/auto-spies#77]
**Is your feature request related to a problem? Please describe.**
I have a class function that takes in an argument and returns a different set of values in an observable (but of the same type) based on that argument:
```ts
// the function I want to mock
getValue(key: string): Observable<string> { /* ... */ }

// the test
mockObj.getValue.withArgs('This').and.nextWith('ThisThing'); // nextWith is not defined
```

**Describe the solution you'd like**
I'd like to have the ability to write code like this:

```ts
mockObj.getValue.withArgs('This').and.nextWith('ThisThing');
mockObj.getValue.withArgs('That').and.nextWith('ThatThing');
```

**Describe alternatives you've considered**
I'm not sure of any alternatives. Perhaps there's even already a way to accomplish this?

**Comment by shairez** [comment]
Yes we implemented it with `calledWith` and `mustBeCalledWith`

Like in here - 
https://github.com/hirezio/auto-spies/tree/master/packages/jest-auto-spies#-calledwith---conditional-return-values

So closing it as it already has an implementation

Thanks!

**Comment by Zooce** [comment]
Oh wow, this is embarrassing lol! No idea why I didn't catch that. Noob mistake...thank you!

**Comment by shairez** [comment]
no worries, glad I could help!
